project_id = "oonepfqgzpdssfzvokgk"

[functions.test-clerk-jwt]
verify_jwt = false

[functions.update-api-config]
verify_jwt = false

[functions.backtest-proxy]
verify_jwt = false

[functions.angel-one-auth]
verify_jwt = false

[functions.angel-one-oauth-callback]
verify_jwt = false

[functions.angel-one-oauth-init]
verify_jwt = false

[functions.sync-clerk-users]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-check-status]
verify_jwt = false
